CREATE TABLE "User" (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       email varchar(50) NOT NULL UNIQUE,
       name varchar(50) NOT NULL,
       lastname varchar(50),
       role varchar(20) NOT NULL,
       password varchar(50) NOT NULL,
       photo varchar(1000),
       registration_date timestamp
   );

   CREATE TABLE Lesson(
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       date timestamp NOT NULL,
       teacher_id int REFERENCES "User"(id) ON DELETE CASCADE,
       topic varchar(50),
       link varchar(1000)
   );

   CREATE TABLE Subscription(
         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         type varchar(20) NOT NULL,
         lessons_rest int,
         start_date timestamp,
         end_date timestamp
   );

   CREATE TABLE Family(
         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         student_id int REFERENCES "User"(id) ON DELETE CASCADE,
         parent_id int REFERENCES "User"(id) ON DELETE CASCADE,
         teacher_id int REFERENCES "User"(id) ON DELETE CASCADE,
         sub_id int REFERENCES Subscription(id) ON DELETE CASCADE
   );

   CREATE TABLE Attendance(
          lesson_id int REFERENCES Lesson(id) ON DELETE CASCADE,
          family_id int REFERENCES Family(id) ON DELETE CASCADE,
          presence boolean NOT NULL,
          family_comment varchar(1000),
          teacher_comment varchar(1000)
   );
